name: kinnow_mqtt
description: A Mqtt 5 client designed with lifecycle management and IoT in mind.
version: 0.0.4
repository: https://github.com/zain-noman/kinnow_mqtt

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  async: ^2.11.0
  protobuf: ^3.1.0
  mutex: ^3.1.0
  crclib: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
