name: kinnow_mqtt
description: A mqtt 5 client
version: 0.0.1
repository: https://github.com/zain-noman/kinnow_mqtt

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  async: ^2.11.0
  isar: ^3.1.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12
